### ISSUE TITLE
Síntesis-DiegoAlexisCarlosCruz

### ISSUE THREAD

**Issue by DiegoSCP117** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-DiegoSCP117#1]
[SíntesisGestiónDeProyectos - Diego Alexis Carlos Cruz.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-DiegoSCP117/files/12685676/SintesisGestionDeProyectos.-.Diego.Alexis.Carlos.Cruz.pdf)

**Comment by mel-16** [comment]
20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
